# Generated by Django 5.2.7 on 2026-03-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_alter_dealer_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered')], default='draft', max_length=50),
        ),
    ]
