# Generated by Django 5.2.7 on 2026-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0007_order_status_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='DEFAULT_CODE', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
